import { useMemo } from 'react';
import { useQuery } from '@tanstack/react-query';
import { getWalletPortfolio, type SimEvmBalance } from '../../api';
import type { AuthState } from '../../hooks/useWalletApp';

type WalletScreenProps = {
  auth: AuthState;
};

function formatUsd(value: number): string {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(value);
}

export function WalletScreen({ auth }: WalletScreenProps) {
  const walletAddress = auth.wallet?.address ?? auth.wallet?.chainAccounts?.[0]?.address ?? '';
  const dailyReport = 'BTC is pulling back while ETH liquidity remains steady. Keep risk exposure tight today.';

  const { data, isLoading, isError, error } = useQuery({
    queryKey: ['wallet-portfolio'],
    queryFn: () => getWalletPortfolio(),
    enabled: Boolean(walletAddress),
    staleTime: 60_000,
  });

  const holdings = useMemo<SimEvmBalance[]>(() => {
    if (!data) {
      return [];
    }

    return [...data.holdings]
      .sort((a, b) => Number(b.value_usd ?? 0) - Number(a.value_usd ?? 0))
      .slice(0, 10);
  }, [data]);

  const totalBalance = data?.totalUsd ?? 0;

  return (
    <section className="mx-auto flex min-h-screen w-full max-w-[420px] flex-col gap-5 p-6">
      <header>
        <h1 className="m-0 text-xl font-bold tracking-tight">Wallet</h1>
      </header>

      <section>
        <p className="m-0 text-base text-base-content/60">Balance</p>
        <p className="m-0 mt-1 text-3xl font-bold leading-none">{formatUsd(totalBalance)}</p>
      </section>

      <section className="grid grid-cols-3 gap-3">
        <button type="button" className="btn btn-primary h-16 text-base font-semibold">
          Top up
        </button>
        <button type="button" className="btn btn-primary h-16 text-base  font-semibold">  
          Transfer
        </button>
        <button type="button" className="btn btn-primary h-16 text-base font-semibold">
          Trade
        </button>
      </section>

      <section className="border border-base-400 bg-base-100 p-4">
        <h2 className="m-0 text-lg font-bold">Today</h2>
        <p className="m-0 mt-2 text-base leading-snug">{dailyReport}</p>
        <p className="m-0 mt-2 text-sm text-base-content/50">Generated by your exclusive agent</p>
        <div className="mt-2 flex items-center justify-between border-t border-base-400 pt-3 text-sm">
          <button type="button" className="link">
            More readings
          </button>
          <button type="button" className="link">
            Saved
          </button>
        </div>
      </section>

      <section className="flex flex-col gap-4">
        <h2 className="m-0 text-xl font-bold">Holdings</h2>

        {isLoading && (
          <div className="border border-base-400 bg-base-100 p-4 text-xl">Loading assets...</div>
        )}
        {isError && (
          <div className="border border-error bg-error/10 p-4 text-xl text-error">
            Failed to load assets: {(error as Error).message}
          </div>
        )}
        {!isLoading && !isError && holdings.length === 0 && (
          <div className="border border-base-400 bg-base-100 p-4 text-xl">No assets found</div>
        )}
        {holdings.map((asset) => (
          <article key={`${asset.chain_id}-${asset.address}`} className="border border-base-400 bg-base-100 p-4">
            <div className="flex items-center justify-between gap-3">
              <div>
                <p className="m-0 text-2xl font-semibold">{asset.symbol ?? asset.name ?? 'Unknown'}</p>
                <p className="m-0 mt-1 text-lg text-base-content/60">{asset.name ?? 'Token'}</p>
              </div>
              <div className="text-right">
                <p className="m-0 text-2xl font-semibold">{formatUsd(Number(asset.value_usd ?? 0))}</p>
                <p className="m-0 mt-1 text-lg text-base-content/60">{Number(asset.amount ?? 0).toFixed(4)}</p>
              </div>
            </div>
          </article>
        ))}
      </section>
    </section>
  );
}
